django/1_quotations/quotations/urls.py
from django.contrib import admin
from django.urls import path
from create_quotations.views import view_quotation, create_quotation, quotations_list, equipments_list, add_product, edit_quotation


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', quotations_list, name='quotations_list'),
    path('create_quotation/', create_quotation, name='create_quotations'),
    path('equipments_list/<uuid:tracking_uuid>/', equipments_list, name='equipments_list'),
    path('add_product/<uuid:tracking_uuid>/', add_product, name='add_product'),
    path('edit_quotation/<uuid:tracking_uuid>/', edit_quotation, name='edit_quotation'),
    path('quotation_view/<uuid:tracking_uuid>/', view_quotation, name='quotation_view'),
]

django/1_quotations/create_quotations/models.py
import uuid
from django.db import models
from create_quotations.calc_module.utils import math, data_loader

# Create your models here.


class Quotation(models.Model):
    tracking_uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    proposal_id = models.CharField(verbose_name="Código da Proposta", max_length=200, null=False, blank=False)
    quotation_version = models.CharField(auto_created=True, default="A", max_length=2, editable=False)
    client_name = models.CharField(verbose_name="Nome do Cliente", max_length=200, null=False, blank=False)
    contribution_margin = models.DecimalField(verbose_name="Margem de Contribuição(%)", max_digits=5, decimal_places=2, default=30.00, null=False, blank=False)    
    vendor_comission = models.DecimalField(verbose_name="Comissão de Venda(%)", max_digits=5, decimal_places=2, default=1.00, null=False, blank=False)    
    state = models.CharField(verbose_name="Estado da Venda", null=False, blank=False, max_length=200,
                             choices=[("MG", "Minas Gerais"),
                                      ("SP", "São Paulo")])
    
    difal_check = models.CharField(verbose_name="Difal?", null=False, blank=False, max_length=3, default="Não",
                                   choices=[("Sim", "Sim"),
                                            ("Não", "Não")])

class Product(models.Model):
    quotation = models.ForeignKey(Quotation, related_name='products', on_delete=models.CASCADE)
    product_type = models.CharField(verbose_name="Tipo", null=False, blank=False, max_length=200, 
                                   choices= [("TA", "Tanque para Armazenamento"),
                                             ("TA", "Tanque Agitador"),
                                             ("VP", "Vaso de Pressão"),
                                             ("SE", "Serviço")])
    product_model = models.CharField(verbose_name="Modelo", null=False, blank=False, max_length=200, 
                                   choices= [("FPTE", "Fundo Plano/Tampo Elíptico"),
                                             ("FPTP", "Fundo Plano/Tampo Plano"),
                                             ("FETE", "Fundo Elíptico/Tampo Elíptico"),
                                             ("MAN", "Manutenção" )])
    
    class Meta:
        abstract = True #Define como uma classe abstrata, não será criada uma tabela para ela.

class Tank(Product):
    diameter = models.IntegerField(verbose_name="Diâmetro Interno", null=False, blank=False, 
                                   choices= [(1000, "1000 mm"),
                                             (2500, "2500 mm")])
    cylindrical_length = models.IntegerField(verbose_name="Comprimento Cilíndrico",
                                             null=False, blank=False)
    volume = models.IntegerField(verbose_name="Volume", null=True, blank=True)
    
    def calculate_volume(self):
        return round(math.calculate_volume_tank(self.diameter, self.cylindrical_length), 2)
    
    def save(self, *args, **kwargs):
        """Sobrescreve o método save para calcular o volume automaticamente"""
        self.volume = self.calculate_volume()  # Calcula o volume e atribui ao campo
        super().save(*args, **kwargs)  # Salva a instância no banco de dados

django/1_quotations/create_quotations/forms.py
from django import forms
from .models import Tank, Quotation

class QuotationForm(forms.ModelForm):
    class Meta:
        model = Quotation
        fields = '__all__'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Tank
        fields = '__all__'
        exclude = ['quotation', 'volume']

django/1_quotations/create_quotations/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import ProductForm, QuotationForm
from .models import Quotation

def quotations_list(request):
    quotations = Quotation.objects.all() #Pega todas as quotations do banco;
    
    return render(request, 'create_quotations/quotations_list.html', {"quotations": quotations})

def equipments_list(request, tracking_uuid):
    quotation = get_object_or_404(Quotation, tracking_uuid=tracking_uuid)
    
    equipments = quotation.equipments.all()
    
    return render(request, 'create_quotations/equipments_list.html', 
                  {"quotation": quotation,
                   "equipments": equipments})

def create_quotation(request):
    quotation_form = QuotationForm()
    
    if request.method == "POST":
        quotation_form = QuotationForm(request.POST)
        if quotation_form.is_valid():
            quotation = quotation_form.save()
            
            return redirect('add_product', tracking_uuid=quotation.tracking_uuid)
            
    return render(request, 'create_quotations/quotation_form.html', {"quotation_form": quotation_form})        

def add_product(request, tracking_uuid):
    quotation = get_object_or_404(Quotation, tracking_uuid=tracking_uuid) #Busca a quotation no banco
    products = quotation.products.all() #busca todos os produtos relacionado a esta quotation no banco

    #Método POST é um tipo de solicitação HTTP utilizada para enviar dados para um servidor.
    if request.method == "POST": 
        # É criada uma instancia do formulário utilizando os dados enviados pelo método POST, que é estruturado como um dicionário
        # Estamos dizendo ao Django: "Use os dados do formulário que o usuário enviou para preencher o formulário original.
        form = ProductForm(request.POST) 
        # Após a instancia ter sido criada com os dados recebidos, é verificado se os dados estão dentro do esperado pelo formulário original.
        if form.is_valid():
            product = form.save(commit=False) #Salva o formulario do produto em product
            product.quotation = quotation # Associa o produto ao orçamento
            product.save() # Salva o produto
            
            return redirect('edit_quotation', tracking_uuid=tracking_uuid)
    else:
        form = ProductForm()
                            
    return render(request, 'create_quotations/product_form.html',
                  {"quotation": quotation,
                   "products": products,
                   "product_form": form,
                   })

def edit_quotation(request, tracking_uuid):
    #Procura um objeto Quotation no banco de dados, que id seja igual a id recebida.
    quotation = get_object_or_404(Quotation, tracking_uuid=tracking_uuid)
    products = quotation.products.all()
    
    return render(request, 'create_quotations/quotation_edit.html', {'quotation': quotation,
                                                                     'products': products})

def view_quotation(request, tracking_uuid):
    #Procura um objeto Quotation no banco de dados, que id seja igual a id recebida.
    quotation = get_object_or_404(Quotation, tracking_uuid=tracking_uuid)
    products = quotation.products.all()
    
    
    return render(request, 'create_quotations/quotation_view.html', {'quotation': quotation,
                                                                     'products': products})

django/1_quotations/create_quotations/templates/base.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}{% endblock page_title %} - FIBRAV</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>
    <nav class="navbar border-bottom border-body mb-4" style="background-color: #003366;" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand"  href="{% url 'quotations_list' %}">
            <img src="{% static 'logo.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
            <span class="ms-3">Orçamentos</span>
          </a>
        </div>
      </nav>

      <main class="container">
        {% block content %}{% endblock content %}
      </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock extra_js %}
  </body>
</html> 

django/1_quotations/create_quotations/templates/create_quotations/equipments_list.html
{% extends "base.html" %}

{% block page_title %}
    Detalhes do orçamento - Equipamentos
{% endblock page_title %}

{% block content %}
    <h2>{{quotation.proposal_id}} - Revisão {{quotation.quotation_version}}</h2>
    <p><strong>Nome do Cliente:</strong> {{ quotation.client_name }}</p>
    <p><strong>Data de Criação:</strong> {{ quotation.creation_date }}</p>

    <a href="{% url "insert_product" %}" class="btn btn-success">Adicionar produto</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Tipo</th>
            <th scope="col">Modelo</th>

        </tr>
        </thead>
        <tbody>
            {% for equipment in equipments %}
                <tr>
                    <th scope="row">{{ equipment.id }}</th>
                    <td>{{ equipment.product_type }}</td>
                    <td>{{ equipment.procut_model }}</td>

                </tr>
            {% empty %}
            <tr>
                <td colspan="5">Nenhum equipamento encontrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

django/1_quotations/create_quotations/templates/create_quotations/product_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}

    Criar Orçamento

{% endblock page_title %}

{% block content %}    

    <h2>{{ quotation.client_name }}</h2> 
    <p>Orçamento: {{ quotation.proposal_id }}</p>


    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                {{ product_form.product_type|as_crispy_field  }}
                {{ product_form.product_model|as_crispy_field  }}
            </div>
            <div class="col-md-4">
  
            </div>
        </div>

            <button type="submit" class="btn btn-success" >Adicionar equipamento</button>
        <hr>
    </form>
    
{% endblock content %}

django/1_quotations/create_quotations/templates/create_quotations/quotation_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}

    Editar Orçamento

{% endblock page_title %}

{% block content %}      

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p><strong>Código da Proposta:</strong> {{ quotation.proposal_id }}</p>
                <p><strong>Data de Criação:</strong> {{ quotation.creation_date }}</p>
                <p><strong>Versão:</strong> {{ quotation.quotation_version }}</p>
            </div>
            <div class="col-md-4">
                <p><strong>Nome do Cliente:</strong> {{ quotation.client_name }}</p>
                <p><strong>Comissão:</strong> {{ quotation.vendor_comission }}%</p>
            </div>
            <div class="col-md-4">
                <p><strong>Estado da Venda:</strong> {{ quotation.get_state_display }}</p>
                <p><strong>DIFAL:</strong> {{ quotation.get_difal_check_display }}</p>
            </div>
        </div>
    </div>
        
    <h3>Produtos</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Modelo</th>
                <th>Volume</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.product_type }}</td>
                <td>{{ product.product_model }}</td>
                <td>{{ product.volume }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Nenhum produto adicionado ainda.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url "add_product" quotation.tracking_uuid %}" class="btn btn-success">Adicionar produto</a>

    
{% endblock content %}

django/1_quotations/create_quotations/templates/create_quotations/quotation_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}

    Criar Orçamento

{% endblock page_title %}

{% block content %}      

    <form method="post">
        {% csrf_token %}

        {{ quotation_form|crispy }}
        <hr>
        
    <h3>Produtos</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Preço Unitário</th>
                <th>Preço Total</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.product_type }}</td>
                <td>{{ product.product_model }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Nenhum produto adicionado ainda.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="submit" class="btn btn-success" >Adicionar equipamentos</button>
</form>
    
{% endblock content %}

django/1_quotations/create_quotations/templates/create_quotations/quotation_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}

    Visualizar Orçamento

{% endblock page_title %}

{% block content %}      

    <p><strong>Código da Proposta:</strong> {{ quotation.proposal_id }}</p>
    <p><strong>Data de Criação:</strong> {{ quotation.creation_date }}</p>
    <p><strong>Versão:</strong> {{ quotation.quotation_version }}</p>
    <p><strong>Nome do Cliente:</strong> {{ quotation.client_name }}</p>
    <p><strong>Comissão:</strong> {{ quotation.vendor_comission }}%</p>
    <p><strong>Estado da Venda:</strong> {{ quotation.get_state_display }}</p>
    <p><strong>DIFAL:</strong> {{ quotation.get_difal_check_display }}</p>
    
    <hr>

    <h3>Produtos</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Diâmetro</th>
                <th>Comprimento Cilíndrico</th>
                <th>Volume</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.product_type }}</td>
                <td>{{ product.product_model }}</td>
                <td>{{ product.diameter }}</td>
                <td>{{ product.cylindrical_length }}</td>
                <td>{{ product.volume }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Nenhum produto adicionado ainda.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
{% endblock content %}

django/1_quotations/create_quotations/templates/create_quotations/quotations_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}

Lista de Orçamentos

{% endblock page_title %}

{% block content %}      

<a href="{% url "create_quotations" %}" class="btn btn-success">Novo Orçamento</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID Proposta</th>
            <th scope="col">Revisão</th>
            <th scope="col">Cliente</th>
            <th scope="col">Estado</th>
            <th scope="col">Criado em</th>
        </tr>
        </thead>
        <tbody>
            {% for quotation in quotations %}
                <tr>
                    <th scope="row">{{ quotation.proposal_id }}</th>
                    <td>{{ quotation.quotation_version }}</td>
                    <td>{{ quotation.client_name }}</td>
                    <td>{{ quotation.get_state_display }}</td>
                    <td>{{ quotation.creation_date|default:"-"|date:"d/m/Y H:i" }}</td>
                    <td>
                      <a href="{% url 'quotation_view' quotation.tracking_uuid %}" class="btn btn-secondary btn-sm">Ver detalhes</a>
                    </td>
                </tr>
            {% empty %}
            <tr>
                <td colspan="5">Nenhum orçamento encontrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}